name: Publish to NuGet
on:
  push:
    branches:
      - master
      
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Publish
      - name: publish on version change
        id: publish_nuget
        uses: brandedoutcast/publish-nuget@v2
        with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: ImmoVlanAPI/ImmoVlanAPI.csproj

          # Configuration to build and package
          BUILD_CONFIGURATION: Release

          # NuGet package id, used for version detection & defaults to project name
          PACKAGE_NAME: ImmoVlanAPI

          # API key to authenticate with NuGet server
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
